export const OPCODES = [
  { m: 'BRK', mode: '#Immediate', size: 2 },
  { m: 'ORA', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ORA', mode: 'Zero Page', size: 2 },
  { m: 'ASL', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'PHP', mode: 'Implied', size: 1 },
  { m: 'ORA', mode: '#Immediate', size: 2 },
  { m: 'ASL', mode: 'Accumulator', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ORA', mode: 'Absolute', size: 3 },
  { m: 'ASL', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BPL', mode: 'Relative', size: 2 },
  { m: 'ORA', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ORA', mode: 'Zero Page,X', size: 2 },
  { m: 'ASL', mode: 'Zero Page,X', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CLC', mode: 'Implied', size: 1 },
  { m: 'ORA', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ORA', mode: 'Absolute,X', size: 3 },
  { m: 'ASL', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'JSR', mode: 'Absolute', size: 3 },
  { m: 'AND', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BIT', mode: 'Zero page', size: 2 },
  { m: 'AND', mode: 'Zero Page', size: 2 },
  { m: 'ROL', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'PLP', mode: 'Implied', size: 1 },
  { m: 'AND', mode: '#Immediate', size: 2 },
  { m: 'ROL', mode: 'Accumulator', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BIT', mode: 'Absolute', size: 3 },
  { m: 'AND', mode: 'Absolute', size: 3 },
  { m: 'ROL', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BMI', mode: 'Relative', size: 2 },
  { m: 'AND', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'AND', mode: 'Zero Page,X', size: 2 },
  { m: 'ROL', mode: 'Zero Page,X', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'SEC', mode: 'Implied', size: 1 },
  { m: 'AND', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'AND', mode: 'Absolute,X', size: 3 },
  { m: 'ROL', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'RTI', mode: 'Implied', size: 1 },
  { m: 'EOR', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'EOR', mode: 'Zero Page', size: 2 },
  { m: 'LSR', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'PHA', mode: 'Implied', size: 1 },
  { m: 'EOR', mode: '#Immediate', size: 2 },
  { m: 'LSR', mode: 'Accumulator', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'JMP', mode: 'Absolute', size: 3 },
  { m: 'EOR', mode: 'Absolute', size: 3 },
  { m: 'LSR', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BVC', mode: 'Relative', size: 2 },
  { m: 'EOR', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'EOR', mode: 'Zero Page,X', size: 2 },
  { m: 'LSR', mode: 'Zero Page,X', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CLI', mode: 'Implied', size: 1 },
  { m: 'EOR', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'EOR', mode: 'Absolute,X', size: 3 },
  { m: 'LSR', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'RTS', mode: 'Implied', size: 1 },
  { m: 'ADC', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ADC', mode: 'Zero Page', size: 2 },
  { m: 'ROR', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'PLA', mode: 'Implied', size: 1 },
  { m: 'ADC', mode: '#Immediate', size: 2 },
  { m: 'ROR', mode: 'Accumulator', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'JMP', mode: '(Indirect)', size: 3 },
  { m: 'ADC', mode: 'Absolute', size: 3 },
  { m: 'ROR', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BVS', mode: 'Relative', size: 2 },
  { m: 'ADC', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ADC', mode: 'Zero Page,X', size: 2 },
  { m: 'ROR', mode: 'Zero Page,X', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'SEI', mode: 'Implied', size: 1 },
  { m: 'ADC', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'ADC', mode: 'Absolute,X', size: 3 },
  { m: 'ROR', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'STA', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'STY', mode: 'Zero Page', size: 2 },
  { m: 'STA', mode: 'Zero Page', size: 2 },
  { m: 'STX', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'DEY', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'TXA', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'STY', mode: 'Absolute', size: 3 },
  { m: 'STA', mode: 'Absolute', size: 3 },
  { m: 'STX', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BCC', mode: 'Relative', size: 2 },
  { m: 'STA', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'STY', mode: 'Zero Page,X', size: 2 },
  { m: 'STA', mode: 'Zero Page,X', size: 2 },
  { m: 'STX', mode: 'Zero Page,Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'TYA', mode: 'Implied', size: 1 },
  { m: 'STA', mode: 'Absolute,Y', size: 3 },
  { m: 'TXS', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'STA', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'LDY', mode: '#Immediate', size: 2 },
  { m: 'LDA', mode: '(Indirect,X)', size: 2 },
  { m: 'LDX', mode: '#Immediate', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'LDY', mode: 'Zero Page', size: 2 },
  { m: 'LDA', mode: 'Zero Page', size: 2 },
  { m: 'LDX', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'TAY', mode: 'Implied', size: 1 },
  { m: 'LDA', mode: '#Immediate', size: 2 },
  { m: 'TAX', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'LDY', mode: 'Absolute', size: 3 },
  { m: 'LDA', mode: 'Absolute', size: 3 },
  { m: 'LDX', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BCS', mode: 'Relative', size: 2 },
  { m: 'LDA', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'LDY', mode: 'Zero Page,X', size: 2 },
  { m: 'LDA', mode: 'Zero Page,X', size: 2 },
  { m: 'LDX', mode: 'Zero Page,Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CLV', mode: 'Implied', size: 1 },
  { m: 'LDA', mode: 'Absolute,Y', size: 3 },
  { m: 'TSX', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'LDY', mode: 'Absolute,X', size: 3 },
  { m: 'LDA', mode: 'Absolute,X', size: 3 },
  { m: 'LDX', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CPY', mode: '#Immediate', size: 2 },
  { m: 'CMP', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CPY', mode: 'Zero Page', size: 2 },
  { m: 'CMP', mode: 'Zero Page', size: 2 },
  { m: 'DEC', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'INY', mode: 'Implied', size: 1 },
  { m: 'CMP', mode: '#Immediate', size: 2 },
  { m: 'DEX', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CPY', mode: 'Absolute', size: 3 },
  { m: 'CMP', mode: 'Absolute', size: 3 },
  { m: 'DEC', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BNE', mode: 'Relative', size: 2 },
  { m: 'CMP', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CMP', mode: 'Zero Page,X', size: 2 },
  { m: 'DEC', mode: 'Zero Page,X', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CLD', mode: 'Implied', size: 1 },
  { m: 'CMP', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CMP', mode: 'Absolute,X', size: 3 },
  { m: 'DEC', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CPX', mode: '#Immediate', size: 2 },
  { m: 'SBC', mode: '(Indirect,X)', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CPX', mode: 'Zero Page', size: 2 },
  { m: 'SBC', mode: 'Zero Page', size: 2 },
  { m: 'INC', mode: 'Zero Page', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'INX', mode: 'Implied', size: 1 },
  { m: 'SBC', mode: '#Immediate', size: 2 },
  { m: 'NOP', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'CPX', mode: 'Absolute', size: 3 },
  { m: 'SBC', mode: 'Absolute', size: 3 },
  { m: 'INC', mode: 'Absolute', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'BEQ', mode: 'Relative', size: 2 },
  { m: 'SBC', mode: '(Indirect),Y', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'SBC', mode: 'Zero Page,X', size: 2 },
  { m: 'INC', mode: 'Zero Page,X', size: 2 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'SED', mode: 'Implied', size: 1 },
  { m: 'SBC', mode: 'Absolute,Y', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: '???', mode: 'Implied', size: 1 },
  { m: 'SBC', mode: 'Absolute,X', size: 3 },
  { m: 'INC', mode: 'Absolute,X', size: 3 },
  { m: '???', mode: 'Implied', size: 1 },
];


export function disassemble(pc, mRead) {
  const opcode = mRead(pc);
  const info = OPCODES[opcode];
  if (!info || info.m === '???') return 'Unknown ($' + opcode.toString(16).toUpperCase().padStart(2, '0') + ')';
  
  const m = info.m;
  const mode = info.mode;
  const size = info.size;
  
  if (size === 1) {
    if (mode === 'A' || mode === 'Accumulator') return m + ' A';
    return m;
  } else if (size === 2) {
    const b1 = mRead((pc + 1) & 0xFFFF);
    const hex1 = '$' + b1.toString(16).toUpperCase().padStart(2, '0');
    if (mode === '#Immediate') return m + ' #' + hex1;
    if (mode === 'Zero Page') return m + ' ' + hex1;
    if (mode === 'Zero Page,X') return m + ' ' + hex1 + ',X';
    if (mode === 'Zero Page,Y') return m + ' ' + hex1 + ',Y';
    if (mode === '(Indirect,X)') return m + ' (' + hex1 + ',X)';
    if (mode === '(Indirect),Y') return m + ' (' + hex1 + '),Y';
    if (mode === 'Relative') {
      // Relative branch target
      let offset = b1;
      if (offset > 127) offset -= 256;
      let target = (pc + 2 + offset) & 0xFFFF;
      return m + ' $' + target.toString(16).toUpperCase().padStart(4, '0');
    }
    return m + ' ' + hex1; // fallback
  } else if (size === 3) {
    const b1 = mRead((pc + 1) & 0xFFFF);
    const b2 = mRead((pc + 2) & 0xFFFF);
    const addr = (b2 << 8) | b1;
    const hexAddr = '$' + addr.toString(16).toUpperCase().padStart(4, '0');
    if (mode === 'Absolute') return m + ' ' + hexAddr;
    if (mode === 'Absolute,X') return m + ' ' + hexAddr + ',X';
    if (mode === 'Absolute,Y') return m + ' ' + hexAddr + ',Y';
    if (mode === '(Indirect)') return m + ' (' + hexAddr + ')';
    return m + ' ' + hexAddr;
  }
  return m;
}
