export const INSTRUCTION_EXPLANATIONS = {
  'LDA': 'Load Accumulator with Memory',
  'LDX': 'Load Index X with Memory',
  'LDY': 'Load Index Y with Memory',
  'STA': 'Store Accumulator in Memory',
  'STX': 'Store Index X in Memory',
  'STY': 'Store Index Y in Memory',
  'TAX': 'Transfer Accumulator to Index X',
  'TAY': 'Transfer Accumulator to Index Y',
  'TXA': 'Transfer Index X to Accumulator',
  'TYA': 'Transfer Index Y to Accumulator',
  'TSX': 'Transfer Stack Pointer to Index X',
  'TXS': 'Transfer Index X to Stack Pointer',
  'PHA': 'Push Accumulator on Stack',
  'PHP': 'Push Processor Status on Stack',
  'PLA': 'Pull Accumulator from Stack',
  'PLP': 'Pull Processor Status from Stack',
  'AND': 'Logical AND Memory with Accumulator',
  'EOR': 'Exclusive-OR Memory with Accumulator',
  'ORA': 'Logical OR Memory with Accumulator',
  'BIT': 'Test Bits in Memory with Accumulator',
  'ADC': 'Add Memory to Accumulator with Carry',
  'SBC': 'Subtract Memory from Accumulator with Borrow',
  'CMP': 'Compare Memory and Accumulator',
  'CPX': 'Compare Memory and Index X',
  'CPY': 'Compare Memory and Index Y',
  'INC': 'Increment Memory by One',
  'INX': 'Increment Index X by One',
  'INY': 'Increment Index Y by One',
  'DEC': 'Decrement Memory by One',
  'DEX': 'Decrement Index X by One',
  'DEY': 'Decrement Index Y by One',
  'ASL': 'Shift Left One Bit (Memory or Accumulator)',
  'LSR': 'Shift Right One Bit (Memory or Accumulator)',
  'ROL': 'Rotate One Bit Left (Memory or Accumulator)',
  'ROR': 'Rotate One Bit Right (Memory or Accumulator)',
  'JMP': 'Jump to New Location',
  'JSR': 'Jump to New Location Saving Return Address',
  'RTS': 'Return from Subroutine',
  'RTI': 'Return from Interrupt',
  'BCC': 'Branch on Carry Clear',
  'BCS': 'Branch on Carry Set',
  'BEQ': 'Branch on Result Zero',
  'BMI': 'Branch on Result Minus',
  'BNE': 'Branch on Result not Zero',
  'BPL': 'Branch on Result Plus',
  'BVC': 'Branch on Overflow Clear',
  'BVS': 'Branch on Overflow Set',
  'CLC': 'Clear Carry Flag',
  'CLD': 'Clear Decimal Mode',
  'CLI': 'Clear Interrupt Disable Bit',
  'CLV': 'Clear Overflow Flag',
  'SEC': 'Set Carry Flag',
  'SED': 'Set Decimal Mode',
  'SEI': 'Set Interrupt Disable Status',
  'BRK': 'Force Break',
  'NOP': 'No Operation'
};

export function getInstructionExplanation(mnemonic) {
  if (!mnemonic || mnemonic === 'unknown') return 'Unknown Opcode';
  // mnemonic might be "STA Abs" or "LDA #", so we extract the first 3 letters
  const baseMnemonic = mnemonic.substring(0, 3).toUpperCase();
  const explanation = INSTRUCTION_EXPLANATIONS[baseMnemonic];
  return explanation ? baseMnemonic + ' - ' + explanation : mnemonic;
}
